### ISSUE TITLE
Run records of the conversion must not contain identifying info

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-hirni#16]
At the moment, things like the center subject ID are likely to end up in path names or other arguments. We need to ensure that the run records that end up in the bids dataset do not contain any identifying information.

That means that we likely cannot use the current  `-s/--spec-file` argument strategy to identify a path  to the to-be-converted data.

I think it would be doable to add a ID->anonID mapping in he studydataset and make `spec2dicom` look up all paths based on this mapping. But I have no idea yet, how to avoid input path values in the run_record.

**Comment by mih** [comment]
Also see https://github.com/datalad/datalad/issues/2577

**Comment by bpoldrack** [comment]
If we could use the mapping during import into the studydataset already, the recorded paths wouldn't contain anything identifying. If we can live with that requirement, this seems to be the most clean and straight-forward approach.

Otherwise, we probably need to have additional studydataset-commands. One would return valid anonID(s) based on some (or none ?) parameter and the other one would return path(s) for given anonID(s).

**Comment by mih** [comment]
I would strongly argue against any constraints impose by a potential later anonymization issue on the content of a raw data repository. In the past I have successfully used solution (2), with no perceived penalty.

**Comment by bpoldrack** [comment]
Ok. So, I'd propose to have those commands, which would return the identity mapping by default and therefore can always and automatically be used by `spec2bids`, whether or not there is an actual mapping provided.

**Comment by mih** [comment]
Addressed via #38
