### ISSUE TITLE
Seemingly superfluous addition of a submodule on `import-dcm`

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-hirni#9]
The subdatset get's a container added as a submodule, but I do not see why this needs to be done. Possibly, this should go into the primary study dataset.

Moreover, there seems to be something going wrong while setting this up:

```
<snip>
[INFO   ] Cloning http://psydata.ovgu.de/cbbs-imaging/conv-container/.git to '/home/data/psyinf/scratch/multires3t/raw/datalad_hirni_import/dicoms/.datalad/environments/import-container' 
[INFO   ] access to dataset sibling "psydata-store" not auto-enabled, enable with:           
|               datalad siblings -d "/home/data/psyinf/scratch/multires3t/raw/datalad_hirni_import/dicoms/.datalad/environments/import-container" enable -s psydata-store 
[INFO   ] Aggregate metadata for dataset /home/data/psyinf/scratch/multires3t/raw/REDACTED/dicoms 
[WARNING] Running find resulted in stderr output: git-annex: ds not found
git-annex: find: 1 failed
<snip>
```

**Comment by bpoldrack** [comment]
The actual idea was to reference a container with the version of the import routine that was used to create that very subdataset. The currently referenced one is wrong of course, but I'm not sure whether this should really go into the studydataset, since those containers could differ across imported acquisitions/sessions/whatever-term-we-eventually-agree-on. To me feels intuitive to bind it to the very thing it's supposed to be associated with.

Re failure: Yes, need to figure out, what that strange `ds` is about.

**Comment by mih** [comment]
That would be fine with me, but at present it adds noise, and it should only do it, if it is actually done in a container -- which is also not the case, right?

**Comment by bpoldrack** [comment]
Agree. Will disable that "experimental" default ...

**Comment by bpoldrack** [comment]
FTR: The repeatedly observed 
```
[WARNING] Running find resulted in stderr output: git-annex: ds not found
git-annex: find: 1 failed
```

is unrelated and fixed in datalad-core PR https://github.com/datalad/datalad/pull/2595

**Comment by mih** [comment]
Import done with #17
