### ISSUE TITLE
webapp does find /js and /css folders 

### ISSUE THREAD

**Issue by pvavra** [psychoinformatics-de/datalad-hirni#98]
running `datalad webapp --dataset . hirni` does start the flask app, but when navigating to `http://127.0.0.1:5000/`, the console shows a bunch of HTTP 404 errors related to the js and css files. And, naturally, I miss the nice formatting visible in the docs.. 

I've installed both datalad and datalad-hirni from github using `pip install git+http:...` 
Using firefox as a browser

tested both locally on my own machine and using port-forwarding from medusa. same results. 

What can I do to debug this?

**Comment by bpoldrack** [comment]
1. Can you post the actual messages here?
2. Since I currently experience difficulties installing something else via `pip install git+https:// ....`, can you try just cloning hirni and then install via `pip install -e .` and see whether this behaves differently?

**Comment by bpoldrack** [comment]
@pvavra : Ignore last comment. I reproduced it. Looking into it.

**Comment by bpoldrack** [comment]
Identified the issue. Those js and css files are in annex and pip isn't aware of that, of course. Probably works for the pypi release, but then again this isn't recent and needs an update within the next days anyway.
Working on a general solution ATM, that would solve it for installing from pypi and from github.

@pvavra : Short term solution for you: Just git clone from here, then run `datalad get .` or `git annex get .` respectively from within that clone and finally install from there (`pip install -e .`).
I'll ping you here, if the real solution is ready.

**Comment by bpoldrack** [comment]
So, my approach didn't really work out. For later reference: Tried to somehow get into distutil's command chain in order to get the files before the machinery starts via subclassing `build` (initially `install_data`). Should be doable in a similar fashion, but ATM takes too much time to gather all necessary information about the internals. Solution might be easy, but at least not obvious to me.

However, this is relevant for installing via cloning (`pip install git+<some url>`) only, whereas a pypi release isn't effected. So - there's a new release now. @pvavra Please try installing via pypi (just `pip install datalad-hirni`). Installing directly from github won't work anytime soon (except for the "manual" workaround I posted in the previous response, of course).
